### ISSUE TITLE
no effect on float left/right items?

### ISSUE THREAD

**Issue by mozbugbox** [chitosai/eye_protector#1]
Don't work well for this site: http://www2.hkej.com/instantnews

It seems the `<div>` style `float: left` caused the problem. change float value to something else make the color shown as expected.

**Comment by chitosai** [comment]
Thanks for reporting.

You're right, float: left moved .wrapper out of \<body\>, thus the white background you see is actually the root \<html\> element. Never excepted anyone would write these weired styles :(

I'll fix it tomorrow, thanks again!

**Comment by mozbugbox** [comment]
It seems that most `computedStyle` are default to `rgba(0, 0, 0, 0)` which means transparent to parent. However, chrome has a default white ground. 

It might help to set the background color for `<html>` tag, such that there is a non blank background color to which other tags, like body, float elements, can fall back.

**Comment by chitosai** [comment]
Thanks for your suggestion!
I've updated the extension, the problem should be fixed after updating to 2.0.6.
