### ISSUE TITLE
建议出release，方便下载安装

### ISSUE THREAD

**Issue by XiaodongLoong** [chitosai/eye_protector#13]

**Comment by chitosai** [comment]
为什么不直接从chrome商店安装？

**Comment by XiaodongLoong** [comment]
chrome商店国内访问不了哇，很多基于chrome内核的浏览器都可以安装
这个插件做的很好

**Comment by XiaodongLoong** [comment]
建议跨平台，能够支持更多的国内chrome内核浏览器的话，流量就上去了

**Comment by chitosai** [comment]
如果都不会翻墙，还指望人家能来github下载crx自己安装吗，我看不太现实吧

国内那些浏览器一般都有自己的扩展发布平台，但是我没精力去维护所有平台，实际上我连chrome/ff/edge三个平台都维护不全
