### ISSUE TITLE
更新Chrome 98之后，插件不再改变google docs文字页背景色了

### ISSUE THREAD

**Issue by HenryandLee** [chitosai/eye_protector#14]
chrome此次更新似乎更改了页面配色样式，如果能看看这个问题会非常感谢！

**Comment by chitosai** [comment]
看了一下，google docs似乎是改用canvas来渲染页面了，已经不是普通的DOMTree了，这我们怕是无能为力了。。

**Comment by HenryandLee** [comment]
明白，不过docs 在这之后开始支持手动修改文档背景了

**Comment by HenryandLee** [comment]
明白，不过docs 在这之后开始支持手动修改文档背景了
