### ISSUE TITLE
表格中的实线加载有问题，edge浏览器，这个是不是有办法可以解决？第一次加载进去

### ISSUE THREAD

**Issue by Chary-zk** [chitosai/eye_protector#19]

**Comment by Chary-zk** [comment]
![K20230504-203518](https://user-images.githubusercontent.com/24539560/236206715-86672e02-80a6-47e1-8f71-8ce45d2ebd3a.png)

**Comment by Chary-zk** [comment]
上述这种情况很明显，看到好多了，这个是不是有解决办法

**Comment by chitosai** [comment]
em，有些具体情况可能很难覆盖，要不还是在这个网站临时关闭一下换色吧

**Comment by Chary-zk** [comment]
好的，谢谢大佬哈

**Comment by chitosai** [comment]
不客气~
