### ISSUE TITLE
Detection a bit too sensitive

### ISSUE THREAD

**Issue by ghost** [chitosai/eye_protector#2]
As I understand, it's supposed to detect bright backgrounds and replace them, but I feel like what the extension considers to be bright is far too sensitive.

**Comment by chitosai** [comment]
Hmmm, reasonable.
I'll offer an option for you to configure brightness detect threshold in next release, maybe next week.

**Comment by chitosai** [comment]
Or 2 years later..
Whatever, finally add this feature :)
